export default {
  SET_TIME: 'SET_TIME',
  SET_LEFT_TO_CLICK: 'SET_LEFT_TO_CLICK',
  SET_SELECTING_INITIAL_SQUARE: 'SET_SELECTING_INITIAL_SQUARE',
  SET_CURRENT_MOVE: 'SET_CURRENT_MOVE',
  SET_CURRENT_LEVEL: 'SET_CURRENT_LEVEL',
  SET_LIVES: 'SET_LIVES',
}
